# Generated by Django 5.0.14 on 2026-07-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='eventtransaction',
            name='is_settlement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventtransaction',
            name='paid_by',
            field=models.CharField(default='You', max_length=100),
        ),
        migrations.AddField(
            model_name='eventtransaction',
            name='split_with',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
