# Generated by Django 5.0.14 on 2026-07-31 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_members_eventtransaction_is_settlement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='members',
        ),
        migrations.RemoveField(
            model_name='eventtransaction',
            name='is_settlement',
        ),
        migrations.RemoveField(
            model_name='eventtransaction',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='eventtransaction',
            name='split_with',
        ),
    ]
